[[categories]]
  name = "2034"
  description = ""

[[categories.subcategories]]
  name = "Expert Discovery Demand"
  description = ""
  format = "D {defandant name} 2034 Demand ({date of exchange})"
  examples = ["D John 2034 Demand (23.12.25)"]

[[categories.subcategories]]
  name = "Expert Discovery Exchange"
  description = ""
  format = "D {defandant name}2034 Exchange ({date of exchange})"
  examples = [""]

[[categories.subcategories]]
  name = "Expert Discovery Designation"
  description = ""
  format = "D 2034 Designation ({date of exchange MM.DD.YY})"
  examples = [""]


[[categories]]
  name = "CORR"
  description = ""

[[categories.subcategories]]
  name = "Correspondence received by CZ from org"
  description = ""
  format = "Ltr from {Organization} re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = []

[[categories.subcategories]]
  name = "Correspondence received by CZ from Client"
  description = ""
  format = "Ltr from {Client name} re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = []

[[categories.subcategories]]
  name = "Correspondence received by CZ from individual"
  description = ""
  format = "Ltr from {Sender Name} re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = []

[[categories.subcategories]]
  name = "Correspondence received by CZ from defence attorney"
  description = ""
  format = "Ltr from D Atty re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = [
    "Ltr from D atty Re Depos 01.02.2020",
    "Ltr from D atty Re Statement of P 03.05.2020",
    "Ltr from D atty Re Offer ($1,500) 02.06.2021",
  ]
[[categories.subcategories]]
  name = "Correspondence received by CZ from"
  description = ""
  format = "Ltr from {Insurance company name} re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = [
    "Ltr from D atty Re Depos 01.02.2020",
    "Ltr from D atty Re Statement of P 03.05.2020",
    "Ltr from D atty Re Offer ($1,500) 02.06.2021",
  ]

[[categories.subcategories]]
  name = "Meet and Confer Correspondence received by CZ"
  description = ""
  format = "M&C Ltr from D Atty Re {brief summary what letter is about (less than 10 words)} {date of letter}"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Auth to demand"
  description = ""
  format = "P {Plantiff name} Auth to Demand (${dollar amount of demand})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Rejected Settlement Offer"
  description = ""
  format = "P {Plaintiff name} (REJECT) Offer (${dollar amount of settlement}) \"{date signed}\""
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Accepted Settlement Offer"
  description = ""
  format = "P {Plaintiff name} (ACCEPT) Offer (${dollar amount of settlement}) \"{date signed}\""
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Deposition Acknowledgment"
  description = ""
  format = "P {Plaintiff name} Acknowledgment Depo and Depo Prep ({date of deposition})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Trial Acknowledgment"
  description = ""
  format = "P {Plaintiff name} Acknowledgment Trial ({date of trial})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Meditation Acknowledgment"
  description = ""
  format = "P {Plaintiff name} Acknowledgment Medtiaion ({date of trial})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ DME Acknowledgment"
  description = ""
  format = "P {Plaintiff name} Acknowledgment DME ({date of trial})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Site Inspection Acknowledgment"
  description = ""
  format = "P {Plaintiff name} Acknowledgment Site Inspection ({date of trial})"
  examples = [""]

[[categories.subcategories]]
  name = "Misc Correspondence received by CZ Past Litigation history"
  description = ""
  format = "P {Plaintiff name} Past Litigation History"
  examples = [""]

[[categories]]
  name = "DEPONOTE"
  description = ""

[[categories.subcategories]]
  name = "Depo Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Ntc Depo {Deponent name} ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Depo & RFP Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Ntc Depo & RFP {Deponent name} ({Depo date})"
  examples = [""]

[[categories.subcategories]]
  name = "Continued Depo Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Cont Ntc Depo & RFP {Deponent name} ({Depo date})"
  examples = [""]

[[categories.subcategories]]
  name = "Continued Depo & RFP Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Cont Ntc Depo & RFP {Deponent name} ({Depo date})"
  examples = [""]


[[categories.subcategories]]
  name = "Amended Depo Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Amended Ntc Depo {Deponent name} ({Depo date})"
  examples = [""]

[[categories.subcategories]]
  name = "Amended Depo & RFP Notices Received by CZ"
  description = ""
  format = "D {Defendant name} Amended Ntc Depo & RFP {Deponent name} ({Depo date})"
  examples = [""]

# Sometimes the letters use response instead of objection
[[categories.subcategories]]
  name = "Depo Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo {Deponent name} ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Person most qualified Depo Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo PMQ ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Person most Knowledgable Depo Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo PMK ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Depo & RFP Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo & RFP {Deponent name} ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Person most qualified Depo & RFP Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo PMQ ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Person most Knowledgable Depo & RFP Objections"
  description = ""
  format = "D {Defandant name} Obj to Ntc Depo PMK ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Request For Production at Deposition Responses Received by CZ"
  description = ""
  format = "D {Defandant name} Resp RFP @ Depo ({Depo Date})"
  examples = [""]


[[categories]]
  name = "DEPOTRANS"
  description = ""

[[categories.subcategories]]
  name = "Deposition Transcripts"
  description = ""
  format = "Depo Trans {Deponent Name} ({Depo Date})"
  examples = []

[[categories.subcategories]]
  name = "Condensed Deposition Transcripts"
  description = ""
  format = "Depo Trans {Deponent Name} ({Depo Date}) -Cond"
  examples = []

[[categories.subcategories]]
  name = "Errata Sheets deponents"
  description = ""
  format = "D {Deponent Name} Errata ({Depo Date})"
  examples = [""]

[[categories.subcategories]]
  name = "Errata Sheets plaintiffs"
  description = ""
  format = "P {Plaintiff Name} Errata ({Depo Date})"
  examples = [""]


[[categories]]
  name = "DISCDEF"
  description = ""

[[categories.subcategories]]
  name = "Form Interrogatories"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to FROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Form Interrogatories"
  description = ""
  format = "D {Defendant name} SUPP {Resp|Obj|Resp and Obj} to FROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Amended Form Interrogatories"
  description = ""
  format = "D {Defendant name} Amended  {Resp|Obj|Resp and Obj} to FROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Further Form Interrogatories"
  description = ""
  format = "D {Defendant name} Further {Resp|Obj|Resp and Obj} to FROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Special Interrogatories"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to SPROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Special Interrogatories"
  description = ""
  format = "D {Defendant name} SUPP {Resp|Obj|Resp and Obj} to SPROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Amended Special Interrogatories"
  description = ""
  format = "D {Defendant name} Amended {Resp|Obj|Resp and Obj} to SPROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Further Special Interrogatories"
  description = ""
  format = "D {Defendant name} Further {Resp|Obj|Resp and Obj} to SPROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Request for Admissions"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to RFA{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Request for Admissions"
  description = ""
  format = "D {Defendant name} SUPP {Resp|Obj|Resp and Obj} to RFA{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Amended Request for Admissions"
  description = ""
  format = "D {Defendant name} Amended {Resp|Obj|Resp and Obj} to RFA{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Further Request for Admissions"
  description = ""
  format = "D {Defendant name} Further {Resp|Obj|Resp and Obj} to RFA{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Request for Production of Documents"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to RFP{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Request for Production of Documents"
  description = ""
  format = "D {Defendant name} SUPP {Resp|Obj|Resp and Obj} to RFP{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Amended Request for Production of Documents"
  description = ""
  format = "D {Defendant name} Amended {Resp|Obj|Resp and Obj} to RFP{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Further Request for Production of Documents"
  description = ""
  format = "D {Defendant name} Further {Resp|Obj|Resp and Obj} to RFP{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Interrogatories"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to SUPP ROGS{set number} P {Plantiff name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Request for Production of Documents"
  description = ""
  format = "D {Defendant name} {Resp|Obj|Resp and Obj} to SUPP RFP{set number} P {Plantiff name}"
  examples = []


[[categories]]
  name = "DISCPL"
  description = "Discovery propounded by Defendant on Plaintiff"

[[categories.subcategories]]
  name = "Form Interogattories"
  description = ""
  format = "D {Defendant name} FROGS{set number}"
  examples = []

[[categories.subcategories]]
  name = "Form Interogattories with more than one plaintiff"
  description = ""
  format = "D {Defendant name} FROGS{set number} to P {Plaintiff Name}"
  examples = []

[[categories.subcategories]]
  name = "Special Interogattories"
  description = ""
  format = "D {Defendant name} SPROGS{set number}"
  examples = []

[[categories.subcategories]]
  name = "Form Interogattories with more than one plaintiff"
  description = ""
  format = "D {Defendant name} SPROGS{set number} to P {Plaintiff Name}"
  examples = []

[[categories.subcategories]]
  name = "Request for production of documents"
  description = ""
  format = "D {Defendant name} RFP{set number}"
  examples = []

[[categories.subcategories]]
  name = "Request for production of ducments with more than one plaintiff"
  description = ""
  format = "D {Defendant name} RFP{set number} to P {Plaintiff Name}"
  examples = []

[[categories.subcategories]]
  name = "Request for Admissions"
  description = ""
  format = "D {Defendant name} RFA{set number}"
  examples = []

[[categories.subcategories]]
  name = "Request for Admissions with more than one plaintiff"
  description = ""
  format = "D {Defendant name} RFA{set number} to P {Plaintiff Name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Interogatories"
  description = ""
  format = "D {Defendant name} SUPP ROGS{set number}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Interogatories with more than one plaintiff"
  description = ""
  format = "D {Defendant name} SUPP ROGS{set number} to P {Plaintiff Name}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Request for Production of Documents"
  description = ""
  format = "D {Defendant name} SUPP RFP{set number}"
  examples = []

[[categories.subcategories]]
  name = "Supplemental Request for Production of Documents"
  description = ""
  format = "D {Defendant name} SUPP RFP{set number} to P {Plaintiff Name}"
  examples = []


[[categories]]
  name = "EXPERTS"
  description = ""

[[categories.subcategories]]
  name = "Defense Medical Exam Reports"
  description = ""
  format = "{Name of doctor}, {doctor title} DME Report ({Date of exam})"
  examples = []

[[categories.subcategories]]
  name = "Independant Medical Exam Reports"
  description = ""
  format = "{Name of doctor}, {doctor title} IME Report ({Date of exam})"
  examples = []

[[categories.subcategories]]
  name = "Defense Medical Exam Nurse Observer Reports"
  description = ""
  format = "Nurse Observer DME Report ({Date of exam})"
  examples = []


[[categories]]
  name = "MEDREC"
  description = ""

[[categories.subcategories]]
  name = "Medicals Records/Reports Single date of service"
  description = "{Date of serivce} Report ({name of facility})"
  format = "{}"
  examples = []

[[categories.subcategories]]
  name = "Medicals Records/Reports Multiple dates of service"
  description = "{start Date of serivce} - {end Date of serivice} Report ({name of facility})"
  format = "{}"
  examples = []

[[categories.subcategories]]
  name = "Medical Bills single date of service"
  description = "{Date of serivce} Bill ({name of facility})"
  format = "{}"
  examples = []

[[categories.subcategories]]
  name = "Medical Bills multiple dates of service"
  description = "{Date of serivce}  - {end Date of serivice} Bill ({name of facility})"
  format = "{}"
  examples = []
